# Generated by Django 3.2.9 on 2021-11-25 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bachelor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=50)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('Year_of_study', models.CharField(default='', editable=False, max_length=50)),
            ],
            options={
                'verbose_name': 'Bachelor',
                'verbose_name_plural': 'Bachelor',
                'db_table': 'Bachelor',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=50)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('espmark', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
                'db_table': 'Terminal',
            },
        ),
    ]
