# Generated by Django 3.2.9 on 2021-11-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='bachelor',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_to_bachaleor.student')),
                ('year', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'bachelor',
                'verbose_name_plural': 'bachelors',
            },
            bases=('student_to_bachaleor.student',),
        ),
        migrations.CreateModel(
            name='terminal',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_to_bachaleor.student')),
                ('espmark', models.FloatField()),
            ],
            options={
                'verbose_name': 'terminal',
                'verbose_name_plural': 't  erminals',
            },
            bases=('student_to_bachaleor.student',),
        ),
    ]
